### ISSUE TITLE
response http status code 500 

### ISSUE THREAD

**Issue by coolmian** [acheong08/ChatGPT-Proxy-V2#1]
When I use V2 Browserless ChatGPT to connect this server, I receive 
```
[GIN] 2023/02/12 - 17:04:03 | 500 |         708µs |       127.0.0.1 | POST     "/completions"
```

**Comment by devmitrandir** [comment]
Me too. It looks like need to create a config.json file in the api folder. But I don't know what the value of the "Endpoint" key should be.

**Comment by acheong08** [comment]
It is kept closed to prevent OpenAI

**Comment by devmitrandir** [comment]
> It is kept closed to prevent OpenAI

I would like to use my own proxy. Apparently I should use your proxy or use v1.

**Comment by coolmian** [comment]
> It is kept closed to prevent OpenAI

Thanks. Whether binary files can be used directly. If so, I want to ask about the system version of the build environment

**Comment by acheong08** [comment]
> Thanks. Whether binary files can be used directly. If so, I want to ask about the system version of the build environment

Yes. Build system is Ubuntu 22.10 AMD64

**Comment by acheong08** [comment]
The binaries work if you want to self host.

**Comment by coolmian** [comment]
@acheong08 Thank you very much for sharing

**Comment by davideuler** [comment]
> 
Thanks a lot.
Could you share nginx config for the reverse proxy?

**Comment by acheong08** [comment]
V2 doesn't work anymore

**Comment by acheong08** [comment]
```nginx
server {



	index index.html index.htm index.nginx-debian.html;

	server_name chat.duti.tech;

	location /api/ {
		proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
		client_max_body_size 0;
		proxy_request_buffering off;
                proxy_read_timeout 300;
		proxy_max_temp_file_size 0;
		proxy_buffering off;
		proxy_no_cache 1; proxy_cache_bypass 1;
		proxy_pass http://localhost:10101/api/;
	}




    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/chat.duti.tech/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/chat.duti.tech/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}



server {
    if ($host = chat.duti.tech) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	listen [::]:80;

	server_name chat.duti.tech;
    return 404; # managed by Certbot


}
```

**Comment by Undrum** [comment]
> ```nginx
> chat
> ```

hi!
I used https://chat.duti.tech/api and got the following response
```json
{"detail":[{"loc":["body","model"],"msg":"field required","type":"value_error.missing"}]}
```

**Comment by acheong08** [comment]
How are you using it?

**Comment by Undrum** [comment]
> ```nginx
> server {
> 
> 
> 
> 	index index.html index.htm index.nginx-debian.html;
> 
> 	server_name chat.duti.tech;
> 
> 	location /api/ {
> 		proxy_set_header Host $host;
>                 proxy_set_header X-Real-IP $remote_addr;
> 		client_max_body_size 0;
> 		proxy_request_buffering off;
>                 proxy_read_timeout 300;
> 		proxy_max_temp_file_size 0;
> 		proxy_buffering off;
> 		proxy_no_cache 1; proxy_cache_bypass 1;
> 		proxy_pass http://localhost:10101/api/;
> 	}
> 
> 
> 
> 
>     listen [::]:443 ssl; # managed by Certbot
>     listen 443 ssl; # managed by Certbot
>     ssl_certificate /etc/letsencrypt/live/chat.duti.tech/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/chat.duti.tech/privkey.pem; # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
> 
> }
> 
> 
> 
> server {
>     if ($host = chat.duti.tech) {
>         return 301 https://$host$request_uri;
>     } # managed by Certbot
> 
> 
> 	listen 80;
> 	listen [::]:80;
> 
> 	server_name chat.duti.tech;
>     return 404; # managed by Certbot
> 
> 
> }
> ```

hi!
I use the v2 version, via https://chat.duti.tech/api PROXY_URL get the following response
```json
{"detail":[{"loc":["body","model"],"msg":"field required","type":"value_error.missing"}]}
```
