### ISSUE TITLE
what's the endpoint ?

### ISSUE THREAD

**Issue by newdots** [acheong08/ChatGPT-Proxy-V2#2]

**Comment by newdots** [comment]
i set this 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/114389694/218362688-8326ee68-4f60-45e0-9b41-ab024a4424fc.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/114389694/218362704-ae2fbb5a-3d0a-4714-990c-95b34de23ddb.png">
but the reply is wrong
<img width="726" alt="image" src="https://user-images.githubusercontent.com/114389694/218362734-d630cbb5-e2ba-4b56-8dc4-a4a2696edad2.png">

**Comment by acheong08** [comment]
Endpoint not public

**Comment by acheong08** [comment]
Use pre-compiled binary

**Comment by newdots** [comment]
where is the binary

**Comment by acheong08** [comment]
In commit history. I'm uploading but slow internet

**Comment by newdots** [comment]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/114389694/218364179-797511eb-f8ea-4c30-8bd1-eed970557a1c.png">
 i run it but  get this reply
i use command : ./ChatGPT-V2

**Comment by newdots** [comment]
my server go env 
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
