### ISSUE TITLE
binary run get error

### ISSUE THREAD

**Issue by newdots** [acheong08/ChatGPT-Proxy-V2#3]
my runtime env

`GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"`

<img width="399" alt="image" src="https://user-images.githubusercontent.com/114389694/218364624-ab1a6392-644a-4f37-bb59-e33e98d8f6e3.png">

**Comment by acheong08** [comment]
It's not bash.

**Comment by acheong08** [comment]
First `chmod +x ChatGPT-V2` then `./ChatGPT-V2`

**Comment by newdots** [comment]
the same
<img width="470" alt="image" src="https://user-images.githubusercontent.com/114389694/218365373-55d7cb4b-850e-445a-b6bd-98e1321cebbf.png">

**Comment by alexandregiordanelli** [comment]
<img width="269" alt="Captura de Tela 2023-02-13 às 01 12 46" src="https://user-images.githubusercontent.com/1518223/218368805-9f066127-477d-4f7f-a926-bea268b46983.png">

**Comment by acheong08** [comment]
It's for Ubuntu 22.10 AMD64

**Comment by newdots** [comment]
can you build a centos binary,thanks

**Comment by Undrum** [comment]
> 

You need to use Wget to download the raw file instead of using git clone.

**Comment by Undrum** [comment]
> <img alt="Captura de Tela 2023-02-13 às 01 12 46" width="269" src="https://user-images.githubusercontent.com/1518223/218368805-9f066127-477d-4f7f-a926-bea268b46983.png">

You need to use Wget to download the raw file instead of using git clone.

**Comment by Undrum** [comment]
> <img alt="Captura de Tela 2023-02-13 às 01 12 46" width="269" src="https://user-images.githubusercontent.com/1518223/218368805-9f066127-477d-4f7f-a926-bea268b46983.png">

You need to use `wget` to download the raw file instead of using git clone."

**Comment by acheong08** [comment]
There is no more usable binary. V2 binary got reverse engineered and the endpoint dissipated
