### ISSUE TITLE
Ubuntu 22.04 can't run the v1 binary

### ISSUE THREAD

**Issue by newdots** [acheong08/ChatGPT-Proxy-V2#5]
my env is Welcome to Ubuntu 22.04.1 LTS
<img width="833" alt="image" src="https://user-images.githubusercontent.com/114389694/218391453-1588351f-3846-4570-adf0-e2ffae73a595.png">

**Comment by newdots** [comment]
my params is 
<img width="309" alt="image" src="https://user-images.githubusercontent.com/114389694/218391739-f68240d5-c18a-4bf8-bdbf-4eac3c3eb051.png">

**Comment by acheong08** [comment]
Bad gateway is not my problem. You didn't host it properly with nginx

**Comment by newdots** [comment]
i just send data with post
the endpoint is 
http://209.141.40.187:10101/completions

**Comment by newdots** [comment]
i don't use nginx
<img width="711" alt="image" src="https://user-images.githubusercontent.com/114389694/218391987-134e7f98-f799-48d8-9bd4-82ed11bef956.png">

**Comment by acheong08** [comment]
That is the problem

**Comment by acheong08** [comment]
You need a reverse proxy. As you can see, it's hosting on 127.0.0.1 which is localhost

**Comment by newdots** [comment]
can u listen it  0.0.0.0

**Comment by acheong08** [comment]
It's for security reasons. Use nginx reverse proxy

**Comment by newdots** [comment]
thanks
